## Summary and discussion

### Conclusions

In line with our regression results (Table \@ref(tab:reg)), we can break our discussion into three sections: race, income, and excluded variables.

#### Race

This regression highlights important conclusions connecting a county's racial composition with its infant mortality rate. The racial categories entered into the regression were Black, Asian, Hispanic, and other, effectively making non-Hispanic White a baseline. As the proportion of the county that is Black increases relative to the other races, the infant mortality rate increases, too. One cannot interpret this effect as an increase in Black residents when the other races are held equal because this regression uses proportions, so more Black people means fewer non-Black people. The general substantive effect holds, though. Similarly, an increase in the other category—a large part of which consists of Native American people—is associated with a higher infant mortality ratio. Interestingly, an increase in the proportion of Hispanic people is associated with a lower infant mortality ratio.

Most of these effects are in line with prior research. Studies suggest that Black children are 2-3 times more likely than non-Hispanic White children to die as infants, and that Native American and Alaska Natives have an infant mortality rate twice as high as non-Hispanic Whites. Prior research has found that Hispanics have an infant mortality rate slightly higher—1.1 times, to be exact—than non-Hispanic Whites, so obtaining a negative effect for this nonrepresentative sample of counties is not too unreasonable.

#### Income

An increase in a county's median income, all else held constant, is associated with a lower infant mortality rate. This mirrors trends found abroad, which suggest that children in wealthier countries are less likely to die as infants. Paradoxically, higher income inequality, as measured through the Gini index, is also associated with lower infant mortality. (Note that the Gini index is bounded between $0$ and $1$, so the substantive effect here is much larger than those of our population-adjusted predictors.) This effect could be more deeply examined in a more representative sample of the counties of the United States.

#### Excluded variables

The potential demographic variables that were either excluded in variable selection or whose effect was not significant at the $\alpha = 0.05$ level are as interesting as the other conclusions. Most notably, measures of healthcare—in this case, the proportions of the population that are insured and uninsured—were excluded in variable selection. One could suppose that insurance status is a proxy for access to healthcare, which would have an impact on infant mortality; however, these predictors were not selected. This could be because their effect was more strongly seen through race, or perhaps because insurance rates did not differ enough between the selected counties. An individual-level analysis could shed light on the impact of insurance.

Similarly, education, sex, and age were left out of the picture. These factors may not differ enough at the county level to make a difference, or perhaps they simply matter less than factors like income and race. The proportion of the population on food stamps was also excluded. Finally, the population itself was excluded, suggesting that infant mortality rates almost scale with the size of the county, as the systems in place to combat such mortality scale, too.

### Limitations

The suppression of data from counties with low infant mortality almost certainly impacted the results. Figure \@ref(fig:map) shows the included counties, which surround cities and have high populations (Figure \@ref(fig:pop)). Much of the Midwest, for instance, is not included in the sample. Generally, the sample of counties was almost certainly not representative of the entire United States, and conclusions should focus on only the most populated counties.

### Future studies

Most notably, future studies need to address the lack of a representative sample. One such solution could be to use data from a multi-year period, over which time many more counties would experience enough infant deaths to bypass the suppression threshold. The type of counties included in the study could then expand, too.

Additionally, future studies could examine individual-level data. A more granular study may reveal deeper and stronger insights, especially as it pertains to race, insurance status, and income.

Finally, broader studies of infant and toddler deaths could shed light on disparities in early childhood care. The CDC only reports infant deaths for the first year of life, but early childhood health may be crucial for longevity and a lifetime of health.
