data:
  outcome:
    raw: ./data/raw/Linked Birth  Infant Death Records, 2017-2018 Expanded.txt
    proc: ./data/processed/outcome_processed.csv
    delim: "\t"
  census:
    raw: ./data/raw/demographics_raw.csv
    proc: ./data/processed/demographics_processed.csv
    delim: ""

sources:
  outcome:
    description: "Infant mortality data"
    name: "CDC WONDER"
    shortname: "CDC"
    url: "wonder.cdc.gov/controller/datarequest/D159"
    variables: ""
    indicators: ["Deaths", "Births", "Death rate"]
    collected: "Download"
    documentation: "wonder.cdc.gov/wonder/help/lbd-expanded.html#"
  census:
    description: "Demographic data"
    name: "American Community Survey"
    shortname: "ACS"
    url: "census.gov/programs-surveys/acs"
    variables: ["B01001_001", "B01001_002", "B01001_026",  # total population, male, female
                "B01001H_001", "B01001B_001", "B01001D_001", "B01001I_001",  # non-hispanic white, black, asian, hispanic
                "B19013_001", "B19083_001", "B22002_002",  # median household income, gini index, received food stamps
                "B23006_002", "B23006_009", "B23006_016", "B23006_023"]  # less than HS, HS, some college, bachelors or higher
    indicators: ["Total population", "Population by sex", "Population by age",
                 "Population by race",
                 "Median household income", "Gini index of income inequality", "Recipients of food stamps",
                 "Education levels",
                 "Health insurance coverage"]
    collected: "`tidycensus` package"
    documentation: "5-year 2019 estimates"

census_long:
  age:
    open: "B01001_0"
    sex:
      men:
        start: 3
        end: 25
      women:
        start: 27
        end: 49
  insurance:
    open: "B27001_0"
    sex:
      men:
        start: 2
        end: 29
      women:
        start: 30
        end: 57

rate: 100000

sections: ["1_project_statement", "2_data_description", "3_exploratory", "4_analysis", "5_discussion", "6_references"]
