---
title: "Final project"
author: "Prayag Gordy"
date: "5/4/2021"
output:
  bookdown::html_document2: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
											message = FALSE,
											warning = FALSE,
											cache = TRUE)
```

```{r}
library(magrittr)
library(ggplot2)

config <- yaml::read_yaml("config.yaml")
invisible(sapply(list.files("R", full.names = TRUE, recursive = TRUE), source, .GlobalEnv))

outcome <- get_outcome()
demographics <- get_census()

lu_county_fips <- demographics %>% 
	dplyr::select(fips, county) %>% 
	tidyr::separate(col = county, into = c("county", "state"), sep = ", ") %>% 
	dplyr::distinct()

df <- demographics %>% 
	tidyr::pivot_wider(id_cols = fips,
										 names_from = variable_name_short,
										 values_from = estimate) %>% 
	dplyr::inner_join(outcome %>% 
											dplyr::filter(variable == "death_rate") %>% 
											tidyr::pivot_wider(id_cols = fips,
																				 names_from = variable,
																				 values_from = estimate),
										by = "fips") %>% 
	dplyr::select(-c(female, above_65))
```

```{r, child = paste0("Rmd/", config$sections, ".Rmd")}
```


